---
- name: "Install prerequisites"
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - lsb-release
    - gnupg
    state: latest
    update_cache: true

- name: "Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker repository to sources list"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
    filename: docker

- name: "Install Docker engine"
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    state: latest
    update_cache: true

- name: "Add {{vagrant_user}} user to Docker group"
  user:
    name: "{{vagrant_user}}"
    append: true
    groups: docker
