# Provisioning playbook

# Updates the APT
# Installs the Docker engine
# Configures the cronjob for fetcher script
# Configures the cronjob for quoter container

---
- name: "Provisioning"
  hosts: all
  become: true
  roles:
    - apt
    - docker
    - fetcher
    - quoter
