---
- name: "Copy quoter directory"
  copy:
    src: ../../../quoter
    dest: "/home/{{vagrant_user}}/"
    owner: "{{vagrant_user}}"
    mode: 0644

- name: "Build quoter Docker image"
  community.general.docker_image:
    build:
      path: "/home/{{vagrant_user}}/quoter"
    name: quoter
    source: build

- name: "Configure cron job to run quoter every hour on it's 15th minute"
  cron:
    name: quoter
    minute: "15"
    hour: "*"
    # I've added the deletion of stopped containers and unused volumes
    # Each quote is appended to the /home/vagrant/quotes.txt file
    job: "docker run -v /tmp/store/file.json:/tmp/quote.json quoter >> /home/{{vagrant_user}}/quotes.txt && docker container prune -f && docker volume prune -af"
    user: "{{vagrant_user}}"
