---
- name: "Copy quoter directory"
  copy:
    src: ../../../quoter
    dest: "/home/{{vagrant_user}}/"
    owner: "{{vagrant_user}}"
    mode: 0644
  when: quoter_docker_image == ""

- name: "Build quoter Docker image"
  community.general.docker_image:
    build:
      path: "/home/{{vagrant_user}}/quoter"
    name: quoter
    source: build
  when: quoter_docker_image == ""

- name: "Configure cron job to run quoter every hour on it's 15th minute with local image and container removal"
  cron:
    name: quoter
    minute: "15"
    hour: "*"
    job: "docker run -v {{last_fetched_file}}:/tmp/quote.json --rm quoter >> /home/{{vagrant_user}}/quotes.txt"
    user: "{{vagrant_user}}"
  when: (quoter_docker_image == "") and (remove_containers == true)

- name: "Configure cron job to run quoter every hour on it's 15th minute with image from registry and container removal"
  cron:
    name: quoter
    minute: "15"
    hour: "*"
    job: "docker run -v {{last_fetched_file}}:/tmp/quote.json --rm {{quoter_docker_image}} >> /home/{{vagrant_user}}/quotes.txt"
    user: "{{vagrant_user}}"
  when: (quoter_docker_image != "") and (remove_containers == true) 

- name: "Configure cron job to run quoter every hour on it's 15th minute with local image and no container removal"
  cron:
    name: quoter
    minute: "15"
    hour: "*"
    job: "docker run -v {{last_fetched_file}}:/tmp/quote.json quoter"
    user: "{{vagrant_user}}"
  when: (quoter_docker_image == "") and (remove_containers == false) 

- name: "Configure cron job to run quoter every hour on it's 15th minute with image from registry and no container removal"
  cron:
    name: quoter
    minute: "15"
    hour: "*"
    job: "docker run -v {{last_fetched_file}}:/tmp/quote.json {{quoter_docker_image}}"
    user: "{{vagrant_user}}"
  when: (quoter_docker_image != "") and (remove_containers == false) 
