---
# last_fetched_file
last_fetched_file: /tmp/fetcher/file.json

# quoter_docker_image is an optional parameter that
# refetences the Docker image for quoter from registry
#
# working example:
# quoter_docker_image: "bgdnr/quoter:latest"
#
quoter_docker_image: ""
